In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [5]:
multisurv_labels = pd.read_csv('multisurv_labels.tsv', sep='\t', index_col=0)
multisurv_labels.head()

             project_id      time  event  group
submitter_id
TCGA-3B-A9HI       SARC  4.167123      0    val
TCGA-3B-A9HJ       SARC  3.024658      0  train
TCGA-3B-A9HL       SARC  1.641096      1  train
TCGA-3B-A9HO       SARC  2.627397      0  train
TCGA-3B-A9HP       SARC  4.457534      1    val

In [8]:

# select only the cancer types BRCA, LUAD, COAD
cancers = ['BRCA', 'LUAD', 'COAD']
selected_sets = multisurv_labels[multisurv_labels['project_id'].isin(cancers)]
selected_sets.head()

             project_id       time  event  group
submitter_id
TCGA-3C-AAAU       BRCA  11.087671      0  train
TCGA-3C-AALI       BRCA  10.972603      0  train
TCGA-3C-AALJ       BRCA   4.038356      0  train
TCGA-3C-AALK       BRCA   3.967123      0  train
TCGA-4H-AAAK       BRCA   0.953425      0  train

In [10]:
# Calculate the number of positive samples in event for each cancer type
positive_samples = selected_sets.groupby(['project_id', 'event', 'group']).size().unstack()
positive_samples

group             test  train  val
project_id event
BRCA       0        91    765   88
           1        17    112   22
COAD       0        35    286   35
           1        10     81   11
LUAD       0        38    257   34
           1        13    154   17

In [11]:
# I want all the submitter_id from the test set
selected_sets_test = selected_sets[selected_sets['group'] == 'test']
selected_sets_test.head()

             project_id      time  event group
submitter_id
TCGA-A1-A0SQ       BRCA  1.517808      0  test
TCGA-A2-A04T       BRCA  6.153425      0  test
TCGA-A2-A0CV       BRCA  8.249315      0  test
TCGA-A2-A0CY       BRCA  4.583562      0  test
TCGA-A2-A0T5       BRCA  1.454795      0  test

In [13]:
# I want to select all the uuuids from Data/TCGA/BRCA, LUAD, COAD that contain these submitter_ids
import os
import json

# Get all the uuids from the test set
uuids_brca = selected_sets_test[selected_sets_test['project_id'] == 'BRCA'].index
uuids_luad = selected_sets_test[selected_sets_test['project_id'] == 'LUAD'].index
uuids_coad = selected_sets_test[selected_sets_test['project_id'] == 'COAD'].index

In [ ]:
path = 'Data/TCGA/'
# create table with all the uuids and sumitter_ids
uuids = []
submitter_ids = []
for cancer in cancers:
    with open(path + cancer + '/meta/clinical.json') as f:
        data = json.load(f)
        for entry in data:
            uuids.append(entry['uuid'])
            submitter_ids.append(entry['submitter_id'])